<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Exercice Require</title>
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <header>
            <h1>
                Entrer
            </h1>
        </header>
        <main>
            <h3>
                La cabane contient des vivres, une carte et un feu encore chaud.
Tu as trouvé un refuge sûr.
            </h3>
            <h4>
               VICTOIRE : Tu survis à la nuit. 
            </h4>
        </main>
    </body>
</html>