<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Exercice Require</title>
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <header>
            <h1>
                Continuer
            </h1>
        </header>
        <main>
            <h3>
                Les herbes mènent à un petit lac clair.
Une barque y flotte doucement.
            </h3>
            <p>
                <a>
                    <li><a href="choix_C1/barque.phtml">Monter dans la barque </a></li>
                    <li><a href="choix_C2/lac.phtml">Contourner le lac</a></li>
                </a>
            </p>
        </main>
    </body>
</html>