<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Exercice Require</title>
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <header>
            <h1>
                Sentier
            </h1>
        </header>
        <main>
            <h3>
                Le sentier serpente jusqu’à une vieille cabane en bois. La porte est entrouverte.
            </h3>
            <p>
                <a>
                    <li><a href="choix_B1/entrer.phtml">entrer </a></li>
                    <li><a href="choix_B2/continuer.phtml">Continuer plus loin dans la forêt</a></li>
                </a>
            </p>
        </main>
    </body>
</html>