<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Exercice Require</title>
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <header>
            <h1>
                Départ
            </h1>
        </header>
        <main>
            <h3>
                Tu te réveilles dans une forêt sombre. Trois chemins s’offrent à toi. Un grondement résonne dans le lointain.
            </h3>
            <p>
                <a>
                    <li><a href="choix_A1/sentier.phtml">Sentier éclairé </a></li>
                    <li><a href="choix_A2/grotte.phtml">Grotte sombre</a></li>
                    <li><a href="choix_A3/buissons.phtml">Buissons mystérieux</a></li>
                </a>
            </p>
        </main>
    </body>
</html>