<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Exercice Require</title>
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <header>
            <h1>
                <?= $TitreSite; ?>      <!--titre du site-->
            </h1>
        </header>
        <main>
            <h2>
                <?= $TitrePage; ?>      <!--titre de page-->
            </h2>
            <p>
               <a href="Depart.phtml">Aller à la page Début </a>     <!--contenu de page-->
            </p>
        </main>
    </body>
</html>
