<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Exercice Require</title>
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <header>
            <h1>
                Contourner le lac
            </h1>
        </header>
        <main>
            <h3>
                Tu t’enfonces dans un marécage invisible.
Impossible d’en sortir.
            </h3>
            <h4>
               DÉFAITE. 
            </h4>
        </main>
    </body>
</html>