<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <title></title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="" />
    </head>
    <body>
        <?php require __DIR__ . '/_accueil.phtml'; ?>
        <?php require __DIR__ . '/_affichage.phtml'; ?>
        <?php require __DIR__ . '/_services.phtml'; ?>
        <?php require __DIR__ . '/_tarifs.phtml'; ?>
        <?php require __DIR__ . '/_contacter.phtml'; ?>
    </body>
</html>