<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Exercice Require</title>
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <header>
            <h1>
                Buissons mystérieux
            </h1>
        </header>
        <main>
            <h3>
                Les buissons s’ouvrent sur une petite clairière illuminée par des lucioles.
Un coffre ancien repose au centre.
            </h3>
            <p>
                <a>
                    <li><a href="choix_B1/coffre.phtml">Ouvrir le coffre </a></li>
                    <li><a href="choix_B2/herbes.phtml">L’ignorer et continuer dans les herbes</a></li>
                </a>
            </p>
        </main>
    </body>
</html>