<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Exercice Require</title>
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <header>
            <h1>
                Toucher le cristal
            </h1>
        </header>
        <main>
            <h3>
                Le cristal te téléporte hors de la forêt.
Tu te sens soudain plus fort et en sécurité.
            </h3>
            <h4>
               VICTOIRE magique. 
            </h4>
        </main>
    </body>
</html>