<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Exercice Require</title>
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <header>
            <h1>
                Avancer plus loin
            </h1>
        </header>
        <main>
            <h3>
               Tu t’enfonces trop profondément : le sol s’effondre.
Tu tombes dans un ravin obscur.
            </h3>
            <h4>
               DÉFAITE. 
            </h4>
        </main>
    </body>
</html>