<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Exercice Require</title>
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <header>
            <h1>
                Ouvrir le coffre
            </h1>
        </header>
        <main>
            <h3>
                Le coffre renferme une dague et un parchemin brûlé.
Un grondement se rapproche.
            </h3>
            <p>
                <a>
                    <li><a href="choix_C1/dague.phtml">Prendre la dague </a></li>
                    <li><a href="choix_C2/parchemin.phtml">Lire le parchemin</a></li>
                </a>
            </p>
        </main>
    </body>
</html>