<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Exercice Require</title>
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <header>
            <h1>
                Demi-tour
            </h1>
        </header>
        <main>
            <h3>
               Tu quittes la grotte avant que quoi que ce soit arrive.
Tu reviens simplement à ton point de départ
            </h3>
            <h4>
               FIN neutre. 
            </h4>
        </main>
    </body>
</html>