<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Exercice Require</title>
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <header>
            <h1>
                Lire le parchemin
            </h1>
        </header>
        <main>
            <h3>
                Le parchemin active un cercle de lumière autour de toi.
La créature disparaît et tu es téléporté en sécurité.
            </h3>
            <h4>
               VICTOIRE. 
            </h4>
        </main>
    </body>
</html>