<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Exercice Require</title>
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <header>
            <h1>
                Continuer
            </h1>
        </header>
        <main>
            <h3>
                Tu marches jusqu’à une clairière où un loup t’observe.
Il grogne et baisse les épaules.
            </h3>
            <p>
                <a>
                    <li><a href="choix_c1/courir.phtml">Courir </a></li>
                    <li><a href="choix_c2/immobile.phtml">Rester immobile</a></li>
                </a>
            </p>
        </main>
    </body>
</html>