<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Exercice Require</title>
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <header>
            <h1>
                avancer
            </h1>
        </header>
        <main>
            <h3>
                La lumière vient d’un cristal bleu posé sur un piédestal.
Il émet une chaleur rassurante.
            </h3>
            <p>
                <a>
                    <li><a href="choix_C1/cristal.phtml">Toucher le cristal </a></li>
                    <li><a href="choix_C2/loin.phtml">Le contourner et avancer plus loin</a></li>
                </a>
            </p>
        </main>
    </body>
</html>