<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Exercice Require</title>
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <header>
            <h1>
                Rester immobile
            </h1>
        </header>
        <main>
            <h3>
                Le loup te renifle puis repart dans l’ombre.
Tu continues prudemment ton chemin vers la sortie de la forêt.
            </h3>
            <h4>
               VICTOIRE. 
            </h4>
        </main>
    </body>
</html>