<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Exercice Require</title>
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <header>
            <h1>
                Grotte sombre
            </h1>
        </header>
        <main>
            <h3>
                La grotte résonne d’un goutte-à-goutte inquiétant.
Une faible lumière apparaît au fond.
            </h3>
            <p>
                <a>
                    <li><a href="choix_B1/avancer.phtml">Avancer vers la lumière </a></li>
                    <li><a href="choix_B2/demi-tour.phtml">Faire demi-tour</a></li>
                </a>
            </p>
        </main>
    </body>
</html>