<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Exercice Require</title>
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <header>
            <h1>
                Barque
            </h1>
        </header>
        <main>
            <h3>
                La barque te mène jusqu’à un village accueillant.
Tu es enfin en sécurité.
            </h3>
            <h4>
               VICTOIRE. 
            </h4>
        </main>
    </body>
</html>