<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Exercice Require</title>
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <header>
            <h1>
                Prendre la dague
            </h1>
        </header>
        <main>
            <h3>
                Une créature bondit des ombres.
La dague ne suffit pas : elle t’emporte.
            </h3>
            <h4>
               DÉFAITE. 
            </h4>
        </main>
    </body>
</html>